### ISSUE TITLE
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:

### ISSUE THREAD

**Issue by mahsayedsalem** [spaceone-dev/homi#22]
**Describe the bug**
I try to follow the example but I always get this error

    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNKNOWN
        details = "Exception calling application: wrapper() missing 1 required positional argument: 'context'"
        debug_error_string = "{"created":"@1596397944.382269000","description":"Error received from peer ipv6:[::1]:50051","file":"src/core/lib/surface/call.cc","file_line":1055,"grpc_message":"Exception calling application: wrapper() missing 1 required positional argument: 'context'","grpc_status":2}"

**To Reproduce**
1. Just follow any example

**Desktop (please complete the following information):**
 - OS: macOs

**Comment by wesky93** [comment]
@mahsayedsalem  thank you so much for use homi & find bug!
I Fix bug and check example is working!
please update version [0.1.1](https://github.com/spaceone-dev/homi/releases/tag/v0.1.1)
but, if you have same bug then please reopen this issue!
