### ISSUE TITLE
Push a final release and archive

### ISSUE THREAD

**Issue by ViridianForge** [spaceone-dev/homi#45]
@wesky93 - While work on the removal of the homi dependency is ongoing for grpc_requests - may I make two requests:

1. Push a final version of homi that includes the click dependency update.
2. Archive this repo as read-only - just to make it abundantly clear that this repo is being sunlit. The public archival will let anyone who still wants to play with it have their fun, but will make it clear that this latest release would be the final one.

**Comment by wesky93** [comment]
https://github.com/wesky93/grpc_requests/pull/3 
I remove homi from grpc_requests
